// Mocks generated by Mockito 5.4.6 from annotations
// in open_vts/test/core/session_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:open_vts/core/storage/token_storage.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [TokenStorageBase].
///
/// See the documentation for Mockito's code generation for more information.
class MockTokenStorageBase extends _i1.Mock implements _i2.TokenStorageBase {
  MockTokenStorageBase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String?> readAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#readAccessToken, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> writeAccessToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#writeAccessToken, [token]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> readImpersonatorToken() =>
      (super.noSuchMethod(
            Invocation.method(#readImpersonatorToken, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> writeImpersonatorToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#writeImpersonatorToken, [token]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> popImpersonatorToken() =>
      (super.noSuchMethod(
            Invocation.method(#popImpersonatorToken, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> clearImpersonatorToken() =>
      (super.noSuchMethod(
            Invocation.method(#clearImpersonatorToken, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> readRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#readRefreshToken, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> writeRefreshToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#writeRefreshToken, [token]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#clearRefreshToken, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
